AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda IoT Stack Template

Parameters:
  CloudwatchNamespace:
    Description: CloudWatch namespace for Tilt metrics
    Type: String
    Default: brewing

  CloudwatchRegion:
    Description: CloudWatch region
    Type: String
    Default: us-west-1

  IoTTopicPrefix:
    Description: IoT topic prefix
    Type: String
    Default: brewing

  BFAPIEndpoint:
    Description: Brewer's Friend API Endpoint URL
    Type: String
    Default: https://log.brewersfriend.com/stream/KEYID


Resources:
  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": "iot:Connect",
              "Resource": "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:*"
            },
            {
              "Effect": "Allow",
              "Action": "iot:Publish",
              "Resource": "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:*"
            },
            {
              "Effect": "Allow",
              "Action": "iot:Subscribe",
              "Resource": "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:*"
            },
            {
              "Effect": "Allow",
              "Action": "iot:Receive",
              "Resource": "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:*"
            }
          ]
        }

  IoTLambdaTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        RuleDisabled: false
        Sql: SELECT topic(2) AS thing_name, state, timestamp() AS timestamp FROM 'brewing/#'
        Actions:
          - Lambda:
              FunctionArn: !GetAtt CWLambdaFunction.Arn
          - Lambda:
              FunctionArn: !GetAtt BFLambdaFunction.Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - iot:Publish
                Resource:
                  - !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/output/*
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:Describe*
                  - cloudwatch:List*
                  - cloudwatch:Get*
                Resource: '*'

  CWLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: iot-to-cloudwatch
      Role: !GetAtt LambdaRole.Arn
      Timeout: 30
      Handler: index.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Environment:
        Variables:
            CLOUDWATCH_NAMESPACE: !Ref CloudwatchNamespace
            CLOUDWATCH_REGION: !Ref CloudwatchRegion
      Code:
        ZipFile: |
            import json
            import boto3
            import os

            cw_namespace = os.getenv('CLOUDWATCH_NAMESPACE', 'test/brewing')
            cw_region = os.getenv('CLOUDWATCH_REGION', 'us-west-1')

            cloudwatch = boto3.client('cloudwatch', region_name=cw_region)

            def cw(deviceId, metricValue, metricName):
                metric_data = {
                    'MetricName': metricName,
                    'Dimensions': [{'Name': 'Location', 'Value': deviceId}],
                    'Unit': 'Count',
                    'Value': float(metricValue)
                }
                cloudwatch.put_metric_data(MetricData=[metric_data],Namespace=cw_namespace)
                return

            def lambda_handler(event, context):
                print("Received event: {}".format(str(event)))
                cw('Tilt ' + event['state']['name'], event['state']['sg'], 'specific_gravity')
                cw('Tilt ' + event['state']['name'], event['state']['temp_f'], 'temperature_f')
                return event

  BFLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: iot-to-brewersfriend
      Role: !GetAtt LambdaRole.Arn
      Timeout: 30
      Handler: index.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Environment:
        Variables:
            API_ENDPOINT: !Ref BFAPIEndpoint
      Code:
        ZipFile: |
            import json
            import os
            from botocore.vendored import requests

            bf_endpoint = os.getenv('API_ENDPOINT', 'https://log.brewersfriend.com/stream/xxx')

            def bf(name, gravity, temp):
                metric_data = {
                    'name': name,
                    'temp': temp,
                    'temp_unit': 'F',
                    'gravity': gravity / 1000.0,
                    'gravity_unit': 'G',

                }
                print("DEBUG: " + bf_endpoint + ", data: " + str(metric_data))
                r = requests.post(url=bf_endpoint, json=metric_data)
                print("bf submit, response code: [{}]".format(r.status_code))
                return r

            def lambda_handler(event, context):
                print("Received event: {}".format(str(event)))
                bf(event['state']['name'], event['state']['sg'], event['state']['temp_f'])
                return event

  CWLambdaInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      SourceArn: !Join [ "", [ "arn:aws:iot:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":rule/", !Ref "IoTLambdaTopicRule" ] ]
      Action: lambda:InvokeFunction
      Principal: iot.amazonaws.com
      FunctionName: !GetAtt CWLambdaFunction.Arn
      SourceAccount: !Ref AWS::AccountId

  BFLambdaInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      SourceArn: !Join [ "", [ "arn:aws:iot:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":rule/", !Ref "IoTLambdaTopicRule" ] ]
      Action: lambda:InvokeFunction
      Principal: iot.amazonaws.com
      FunctionName: !GetAtt BFLambdaFunction.Arn
      SourceAccount: !Ref AWS::AccountId

Outputs:
  CWLambda:
    Description: ARN for CloudWatch Lambda function
    Value: !GetAtt CWLambdaFunction.Arn
  BFLambda:
    Description: ARN for Brewer's Friend Lambda function
    Value: !GetAtt BFLambdaFunction.Arn
